name: Build Publish Main
on:
  push:
    branches:
      - main
      - $default-branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ACTIONS_PAT}}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Bump Package Version
        id: bumping-version
        uses: jpb06/bump-package@latest
        with:
          major-keywords: BUMP MAJOR VERSION
          minor-keywords: feat,BREAKING CHANGE
          patch-keywords: build,chore,ci,docs,fix,perf,refactor,revert,style,test
      - name: Publish Main Version
        if: steps.bumping-version.outputs.bump-performed == 'true'
        run: pnpm run release:main
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
