name: Publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version to set as latest'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm dist-tag add @fp-tx/core@${{github.event.inputs.tag}} latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
